version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
